# First Bambara experiment config
model:
  model_name_or_path: "ylacombe/vits-vctk-with-discriminator" # Required
  config_name: null
  tokenizer_name: "./vits_bam_tokenizer"
  pseudo_ipa: true
  feature_extractor_name: null
  cache_dir: null
  use_fast_tokenizer: true
  model_revision: "main"
  token: null  # Preferably use huggingface-cli login
  trust_remote_code: false
  override_speaker_embeddings: true  # Try overriding speaker embeddings
  override_vocabulary_embeddings: true  # use true if tokenizer != pretraining tokenizer

data:
  project_name: "bam_vits_finetuning"
  dataset_name: "Panga-Azazia/all-in-one" # TODO: replace with actual dataset
  dataset_config_name: "afvoices"
  overwrite_cache: false
  preprocessing_num_workers: 8
  max_train_samples: null
  max_eval_samples: 5000 # Limit the number of eval examples to 5k
  audio_column_name: "audio"
  text_column_name: "text"
  speaker_id_column_name: participantId
  filter_on_speaker_id: null
  max_tokens_length: 450
  max_duration_in_seconds: 20.0
  min_duration_in_seconds: 0.2
  preprocessing_only: false
  train_split_name: "train"
  eval_split_name: "test"
  do_lower_case: true
  do_normalize: false
  full_generation_sample_text: "An ta to jinɛlatigɛ ka nɔgɔya an ma sa. I bɛna maɲuman ko min sɔrɔ nin ko in na. I yɛrɛ lafiya"

training:
  do_train: true
  do_eval: true
  num_train_epochs: 50
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  gradient_checkpointing: false
  learning_rate: 0.001 # Do not use scientific notation since we do not parse them
  adam_beta1: 0.8
  adam_beta2: 0.99
  warmup_ratio: 0.08
  group_by_length: true
  eval_steps: 300
  do_step_schedule_per_epoch: true
  lr_decay: 0.999875
  weight_duration: 1.0
  weight_kl: 1.5
  weight_mel: 35.0
  weight_disc: 3.0
  weight_gen: 1.0
  weight_fmaps: 1.0
  fp16: true
  seed: 456

logging:
  output_dir: "./tmp/bam_vits_finetuning-exp1" # Required: should be unique for each run to avoid accidental overwriting
  overwrite_output_dir: true
  push_to_hub: true
  hub_model_id: diarray/bam_vits_finetuning-exp1
  report_to: "wandb"
  logging_dir: "./logs"
  save_steps: 300
  save_total_limit: 10